version: '3.8'
services:
  database:
    container_name: database
    image: mariadb:latest
    ports:
      - ${MYSQL_TCP_PORT}:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
  phpmyadmin:
    image: phpmyadmin
    ports:
      - ${PMA_PORT}:80
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: ${MYSQL_TCP_PORT}
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}